// import { Inter } from "next/font/google";
import "./globals.css";
// import Header from "./components/Header";
// const inter = Inter({ subsets: ["latin"] });
// import { Theme } from "@radix-ui/themes";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        {/* <body className={inter.className}>
        <Theme accentColor="crimson" grayColor="sand" radius="large" scaling="95%"><Header>{children}</Header></Theme>
        */}
      </body>
    </html>
  );
}
